export const LOGIN_USER_INIT = "LOGIN_USER_INIT";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const BROKER_LOGIN_INIT = "BROKER_LOGIN_INIT";
export const BROKER_LOGIN_SUCCESS = "BROKER_LOGIN_SUCCESS";
export const BROKER_LOGIN_FAIL = "BROKER_LOGIN_FAIL";

export const GET_BROKER_LOGIN_STATUS_INIT = "GET_BROKER_LOGIN_STATUS_INIT";
export const GET_BROKER_LOGIN_STATUS_SUCCESS =
  "GET_BROKER_LOGIN_STATUS_SUCCESS";
export const GET_BROKER_LOGIN_STATUS_FAIL = "GET_BROKER_LOGIN_STATUS_FAIL";

export const GET_OPEN_POSITIONS_INIT = "GET_OPEN_POSITIONS_INIT";
export const GET_OPEN_POSITIONS_SUCCESS = "GET_OPEN_POSITIONS_SUCCESS";
export const GET_OPEN_POSITIONS_FAIL = "GET_OPEN_POSITIONS_FAIL";

export const SQUARE_OFF_ORDER_INIT = "SQUARE_OFF_ORDER_INIT";
export const SQUARE_OFF_ORDER_SUCCESS = "SQUARE_OFF_ORDER_SUCCESS";
export const SQUARE_OFF_ORDER_FAIL = "SQUARE_OFF_ORDER_FAIL";

export const GET_DAY_TRADINGS_DATA_INIT = "GET_DAY_TRADINGS_DATA_INIT";
export const GET_DAY_TRADINGS_DATA_SUCCESS = "GET_DAY_TRADINGS_DATA_SUCCESS";
export const GET_DAY_TRADINGS_DATA_FAIL = "GET_DAY_TRADINGS_DATA_FAIL";

export const GET_DAY_TRADINGS_PANDL_SUCCESS = "GET_DAY_TRADINGS_PANDL_SUCCESS";

export const GET_STRETAGIC_OPTIONS_DATA_INIT =
  "GET_STRETAGIC_OPTIONS_DATA_INIT";
export const GET_STRETAGIC_OPTIONS_DATA_SUCCESS =
  "GET_STRETAGIC_OPTIONS_DATA_SUCCESS";
export const GET_STRETAGIC_OPTIONS_DATA_FAIL =
  "GET_STRETAGIC_OPTIONS_DATA_FAIL";

export const UPDATE_DAY_TRADING_AUTO_TRADE_STATUS_INIT =
  "UPDATE_DAY_TRADING_AUTO_TRADE_STATUS_INIT";
export const UPDATE_DAY_TRADING_AUTO_TRADE_STATUS_SUCCESS =
  "UPDATE_DAY_TRADING_AUTO_TRADE_STATUS_SUCCESS";
export const UPDATE_DAY_TRADING_AUTO_TRADE_STATUS_FAIL =
  "UPDATE_DAY_TRADING_AUTO_TRADE_STATUS_FAIL";

export const UPDATE_DAY_TRADING_CARD_DATA_INIT =
  "UPDATE_DAY_TRADING_CARD_DATA_INIT";
export const UPDATE_DAY_TRADING_CARD_DATA_SUCCESS =
  "UPDATE_DAY_TRADING_CARD_DATA_SUCCESS";
export const UPDATE_DAY_TRADING_CARD_DATA_FAIL =
  "UPDATE_DAY_TRADING_CARD_DATA_FAIL";

export const GET_ORDER_HISTORY_INIT = "GET_ORDER_HISTORY_INIT";
export const GET_ORDER_HISTORY_SUCCESS = "GET_ORDER_HISTORY_SUCCESS";
export const GET_ORDER_HISTORY_FAIL = "GET_ORDER_HISTORY_FAIL";

export const GET_PAPERTRADE_ORDER_HISTORY_INIT = "GET_PAPERTRADE_ORDER_HISTORY_INIT";
export const GET_PAPERTRADE_ORDER_HISTORY_SUCCESS = "GET_PAPERTRADE_ORDER_HISTORY_SUCCESS";
export const GET_PAPERTRADE_ORDER_HISTORY_FAIL = "GET_PAPERTRADE_ORDER_HISTORY_FAIL";

export const GET_POSITIONAL_SIGNAL_SCANNER_DATA_INIT =
  "GET_POSITIONAL_SIGNAL_SCANNER_DATA_INIT";
export const GET_POSITIONAL_SIGNAL_SCANNER_DATA_SUCCESS =
  "GET_POSITIONAL_SIGNAL_SCANNER_DATA_SUCCESS";
export const GET_POSITIONAL_SIGNAL_SCANNER_DATA_FAIL =
  "GET_POSITIONAL_SIGNAL_SCANNER_DATA_FAIL";

export const GET_STRATEGICS_DATA_INIT = "GET_STRATEGICS_DATA_INIT";
export const GET_STRATEGICS_DATA_SUCCESS = "GET_STRATEGICS_DATA_SUCCESS";
export const GET_STRATEGICS_DATA_FAIL = "GET_STRATEGICS_DATA_FAIL";

export const GET_SUBSCRIPTIONS_DATA_INIT = "GET_SUBSCRIPTIONS_DATA_INIT";
export const GET_SUBSCRIPTIONS_DATA_SUCCESS = "GET_SUBSCRIPTIONS_DATA_SUCCESS";
export const GET_SUBSCRIPTIONS_DATA_FAIL = "GET_SUBSCRIPTIONS_DATA_FAIL";

export const GET_CHARTING_DATA_INIT = "GET_CHARTING_DATA_INIT";
export const GET_CHARTING_DATA_SUCCESS = "GET_CHARTING_DATA_SUCCESS";
export const GET_CHARTING_DATA_FAIL = "GET_CHARTING_DATA_FAIL";

export const GET_INTRADAYSTOCK_LIST_DATA_INIT =
  "GET_INTRADAYSTOCK_LIST_DATA_INIT";
export const GET_INTRADAYSTOCK_LIST_DATA_SUCCESS =
  "GET_INTRADAYSTOCK_LIST_DATA_SUCCESS";
export const GET_INTRADAYSTOCK_LIST_DATA_FAIL =
  "GET_INTRADAYSTOCK_LIST_DATA_FAIL";

export const GET_CHARTING_KEY_DATA_INIT = "GET_CHARTING_KEY_DATA_INIT";
export const GET_CHARTING_KEY_DATA_SUCCESS = "GET_CHARTING_KEY_DATA_SUCCESS";
export const GET_CHARTING_KEY_DATA_FAIL = "GET_CHARTING_KEY_DATA_FAIL";

export const GENERATE_CHARTING_KEY_INIT = "GENERATE_CHARTING_KEY_INIT";
export const GENERATE_CHARTING_KEY_SUCCESS = "GENERATE_CHARTING_KEY_SUCCESS";
export const GENERATE_CHARTING_KEY_FAIL = "GENERATE_CHARTING_KEY_FAIL";

export const UPDATE_CHARTING_KEY_STATUS_INIT =
  "UPDATE_CHARTING_KEY_STATUS_INIT";
export const UPDATE_CHARTING_KEY_STATUS_SUCCESS =
  "UPDATE_CHARTING_KEY_STATUS_SUCCESS";
export const UPDATE_CHARTING_KEY_STATUS_FAIL =
  "UPDATE_CHARTING_KEY_STATUS_FAIL";


  export const GET_SYMBOL_LIST_SUCCESS = "GET_SYMBOL_LIST_SUCCESS";
  export const CLEAR_SYMBOL_LIST = "CLEAR_SYMBOL_LIST";

  export const ONE_TOUCH_CREATE_SUCCESS = "ONE_TOUCH_CREATE_SUCCESS";
  export const ONE_TOUCH_CREATE_ERROR = "ONE_TOUCH_CREATE_ERROR";
  export const CHARTING_CLEAR_MESSAGE = " CHARTING_CLEAR_MESSAGE";

  export const GET_PRICES_INDEX_SUCCESS = " GET_PRICES_INDEX_SUCCESS";


export const GET_PAPER_TRADINGS_DATA_INIT = "GET_PAPER_TRADINGS_DATA_INIT";
export const GET_PAPER_TRADINGS_DATA_SUCCESS = "GET_PAPER_TRADINGS_DATA_SUCCESS";
export const GET_PAPER_TRADINGS_DATA_FAIL = "GET_PAPER_TRADINGS_DATA_FAIL";


export const UPDATE_PAPER_TRADING_CARD_DATA_INIT = "UPDATE_DAY_TRADING_CARD_DATA_INIT";
export const UPDATE_PAPER_TRADING_CARD_DATA_SUCCESS = "UPDATE_DAY_TRADING_CARD_DATA_SUCCESS";
export const UPDATE_PAPER_TRADING_CARD_DATA_FAIL = "UPDATE_DAY_TRADING_CARD_DATA_FAIL";

export const GET_PAPER_TRADINGS_TOTALS_DATA_INIT = "GET_PAPER_TRADINGS_TOTALS_DATA_INIT";
export const GET_PAPER_TRADINGS_TOTALS_DATA_SUCCESS = "GET_PAPER_TRADINGS_TOTALS_DATA_SUCCESS";
export const GET_PAPER_TRADINGS_TOTALS_DATA_FAIL = "GET_PAPER_TRADINGS_TOTALS_DATA_FAIL";


export const SET_CUSTOMER_PLAN_STATUS = "SET_CUSTOMER_PLAN_STATUS";